site_name: wizzem api
pages:
- [index.md, Home]
- [user.md, User]
- [friend.md, Friend]
- [notification.md, Notification]
- [session.md, Session]
- [event.md, Event]
- [participant.md, Participant]
- [media.md, Media]
- [comment.md, Comment]
- [like.md, Like]
- [error.md, Error]
theme: 'spacelab'
