site_name: wizzem api
pages:
- [index.md, Accueil]
- [user.md, User]
- [session.md, Session]
- [event.md, Event]
- [participant.md, Participant]
- [media.md, Media]
- [comment.md, Comment]
- [like.md, Like]
theme: united